### ISSUE TITLE
layout overhaul

### ISSUE THREAD

**Issue by khutten** [mrhut10/todaysCuriosity#19]
If someone with design and CSS skills (unlike me) wants to over haul the layout I think that would be great. I think it would be good if the input (source) image was a little bigger as it's useful to see highlighted squares if you are trying to line them up with the eyes for example. But that's my only thoughts one the matter. 

There isn't too many moving parts so I don' think it would take too long for someone who knows what they're doing. But by all means through rough ideas of what you thoughts are before putting time in so no one's time is wasted.

**Comment by TomLandis** [comment]
Hey, I'd like to tackle this if possible?  May I ?

**Comment by khutten** [comment]
Fixed in #23 👏
