### ISSUE TITLE
Create toggle button for two types of image output

### ISSUE THREAD

**Issue by khutten** [mrhut10/todaysCuriosity#26]
Nice easy chuck of work. 

So on line 37ish of `scripts.js`

``` javascript
function imageSetup (img) {
  curiosity.baseImage = img;
  curiosity.paintInputImage();
  curiosity.createBrightpixels();
  // const {inputCanvas, outputCanvas} = curiosity.getReducedPixelBlocks();
  const {inputCanvas, outputCanvas} = curiosity.getReversedPixelBlocks();

  const inputDiv = document.getElementById('input-display');
```

you can see that we are calling a method `getReversedPixelBlocks()` while ignoring `getReducedPixelBlocks()` (it's commented out), but both are valid and both work.

I want a toggle switch on the UI that toggles which method is called here. 🎉 

Same thing will need to be updated on line 61 where `getReversedPixelBlocks()` is called again.

**Comment by xseman** [comment]
I'd like to get this assigned. Thanks!

**Comment by khutten** [comment]
Got for it @xseman, It's all yours.

**Comment by hirotachi** [comment]
i've already done it if you want me to commit it

**Comment by mrhut10** [comment]
@khutten i'll approve both #28 and #27 which both address this issue.

can you please have a look and pick one to merge.

BTW thank you @hirotachi and @xseman both great PR's and welcome to the project really great to have you in the community.

**Comment by khutten** [comment]
Donski, Thanks @xseman @hirotachi 🏅 🏋️
