### ISSUE TITLE
Credit all github contributors for this project (github API)

### ISSUE THREAD

**Issue by khutten** [mrhut10/todaysCuriosity#29]
At the bottom of the project there is credit for myself and @mrhut10, this is hard coded. It would be cool to instead use the github api to fetch anyone who has contributed to this project and display everyone's avatars.

Bonus points if the avatars are also links back to each person's github page.

This idea was suggested by @mrhut10 in #23

**Comment by mrhut10** [comment]
just read the github api documents and looks like will be fairly easy.

actually a few ways to do it

1. json for contributors to the project, avatar, and contribution (by commit) url link [urllink](https://api.github.com/repos/mrhut10/todaysCuriosity/contributors) if someone wanted to read the [documentation](https://developer.github.com/v3/repos/#list-contributors)
2. a little more complicated part of the api will provide the count of contributions by additions/deletions/commits however only for each week. [documentation](https://developer.github.com/v3/repos/statistics/#get-contributors-list-with-additions-deletions-and-commit-counts)

hopefully this is helpful, I'll be available at the end of the week if anyone wants a hand implementing.

**Comment by khutten** [comment]
Fixed in #30 

Thanks @TakeAWalk  👏 👏 👏 👏

**Comment by khutten** [comment]
<img width="734" alt="image" src="https://user-images.githubusercontent.com/42974531/47113620-3c6ccc00-d2a5-11e8-9a28-9f24966c6c09.png">

Looking very nice @TakeAWalk

**Comment by mrhut10** [comment]
on the larger screens that looks so great :)
