### ISSUE TITLE
Mobile friendly layout needed

### ISSUE THREAD

**Issue by mrhut10** [mrhut10/todaysCuriosity#3]
Currently the sliders and set width of page is painful. Will need to address this shortly

**Comment by khutten** [comment]
If anyone wants to jump on this from the hacktober fest, that would be cool.
Who ever works on it is welcome to mix in their own ideas or experience with UI for mobile, but if not I have some suggestions. (probably need to play with the app quickly for this to make sense).

### 1)
At a certain breakpoint get rid of the slider and replace them with number inputs with increment/decrement buttons either side, I think that would work well for being able to tap away or enter a number. (you could even combine the x and y div inputs into one and force the 'sample blocks' to be the same) 🤷‍♀️ 

### 2)
Put the inputs into some kind of expandable menu, perhaps hit the menu button, it expands, you than select which input you want to change, than the menu collapses leaving just the output image and the one input.

### 3)
Change the image layout obviously, so should be vertical, maybe we should even get ride of the input image, but at least have it below the output image.

**Comment by mrhut10** [comment]
apologies i haven't read your last few comments @khutten but i feel like i may have addressed a bunch of the heavy lifting within this one on PR #38 
I'm just addressing two screen-sizes less than 600 px and above 600px

**Comment by mrhut10** [comment]
i'm going to close this one i think we've address a bunch of it and we will continue to work on it
