### ISSUE TITLE
Capping quad size to a perfect rectangle?

### ISSUE THREAD

**Issue by Manny-FFWL** [mrhut10/todaysCuriosity#6]
Hey if you've noticed the images sometimes overlay on top of each other so how about you cap the quad's size to a perfect square(maybe 2x2, 3x3, 4x4 etc) that way it doesn't do that? If it's not an issue you can remove. Thanks

**Comment by mrhut10** [comment]
Sorry can I get you to explain the issue a little more I feel like I'm assuming what you meant but now not certain.

Are you taking about the

**Comment by mrhut10** [comment]
Sorry I didn't mean to close..

**Comment by Manny-FFWL** [comment]
Yeah sure. You see that with Kensuke's example he used perfect squares so why don't you cap the square's size to a value that makes it a perfect square that way even when the sliders are pushed to the max, the square don't overlay which in turn wouldn't make the image messy

**Comment by mrhut10** [comment]
ok @Manny-FFWL i've just relaunched at new url
https://todayscuriosityjs.netlify.com/
which still needs lots of work, but will allow users to use there own image.

now that i've done this i'll experiment with what you've mentioned next week :)

**Comment by khutten** [comment]
I think @mrhut10 Means https://todayscuriosity.netlify.com/ @Manny-FFWL

**Comment by khutten** [comment]
So the x and y sliders can be move separate from one another allowing the user to make very long rectangular image blocks if they like, but maybe we could add a "lock ratio" toggle button so that the x and y div move together?

I'm not really sure what you mean by overlay though?

**Comment by mrhut10** [comment]
@Manny-FFWL I understand what you mean having the x and y locked to each other, which may make for a simplier UI. like @khutten i'm not certain i understand the overlay.

I'm neutral on this change as is and happy to have it go to a vote, 
alternatively I'd be happy to approve if someone makes a PR which locks x/y together and a advanced drop down advanced tab to separate them again if someone really wants too.

**Comment by Manny-FFWL** [comment]
Oh right. Sorry for the late reply. By overlay I mean that sometimes they lay on top of each other creating a nasty effect. It seems to have been solved though! Right now how about you make the quads all perfect squares? I'm a programmer myself but I don't know much JavaScript that's why I can't help

**Comment by khutten** [comment]
I think I might close this issue as not having the x and y divisions locked together is a choice we've made, it is a valid point and I think we'll continue to think about it locking the x and y together.

Thanks for the input @Manny-FFWL 🏅
